---

- name: install
  include: install.yml

- name: configure
  include: config.yml

- stat: path=/etc/init.d/haproxy
  register: haproxy_oldservice

- name: disable service included with package
  service: name=haproxy state=stopped enabled=no
  when: haproxy_oldservice.stat.exists
  ignore_errors: yes

- name: delete service included with package
  file: path=/etc/init.d/haproxy state=absent

- name: service
  include: runit_service.yml
  vars:
    service_name: "{{ haproxy_service_name }}"
    service_user: "{{haproxy_user}}"
    service_command: /usr/sbin/haproxy -db -f {{ haproxy_config_dir }}/haproxy.cfg
    service_env_vars: {}

