---

- name: install
  include: install.yml

- name: configure
  include: config.yml

- stat: path=/etc/init.d/haproxy
  register: haproxy_oldservice

- name: disable service included with package
  service: name=haproxy state=stopped enabled=no
  when: haproxy_oldservice.stat.exists
  ignore_errors: yes

- name: delete service included with package
  file: path=/etc/init.d/haproxy state=absent

- name: service
  include: service.yml
