---

- name: service - setup and run
  runit:
    name: "{{ haproxy_service_name }}"
    enabled: yes
    state: start
    timeout: 10
    user: "{{ haproxy_user }}"
    command: "/usr/sbin/haproxy -db {% for file_name in haproxy_configs %}-f {{ haproxy_config_dir }}/{{ file_name }} {% endfor %}"
    env_vars: {}
  register: haproxy_service_status

